### ISSUE TITLE
Contribute findings and info to main wiki

### ISSUE THREAD

**Issue by gynt** [sourcehold/sourcehold-maps#8]
To keep info simple and organised, I suggest to put all our info on the map file format in the main wiki [here](https://github.com/sourcehold/Sourcehold/wiki/Map-file).

The info that exists already there [(at the time of writing this, this is the info)](https://github.com/sourcehold/Sourcehold/wiki/Map-file/7b22efe1ceb0e13627201cf5b49476ba398518d4) and here should be cross-validated.

Preferably, for new information there, updated python code should be written here.

**Comment by J-T-de** [comment]
As addition, there is now a [wiki branch](https://github.com/sourcehold/sourcehold-maps/tree/wiki) for easier collaboration.

**Comment by gynt** [comment]
Yes, let's upgrade the status of the (new) [wiki branch](https://github.com/sourcehold/sourcehold-maps/tree/wiki) to a full-blown wiki that explains the map file format.

@J-T-de do you know whether everything from the link has been cross-validated? I know you were working on the Events for example. If so, we can close this issue.

**Comment by J-T-de** [comment]
The events did @CIO61. I am quite sure that we have all data in our wiki.
The only exception is one section between the description and the directory. But the stub already exists, and I am also working on it (some parts seem incompatible with Crusader, but lets see) ...

Except if we want to link this in the main repo, we can close this.

**Comment by gynt** [comment]
Sorry @CIO61 !

**Comment by CIO61** [comment]
I shall update the conditions list for specifics(i have the list of which address for a condition corresponds to which, but was lazy when preparing the kaitai file)
